on:
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    environment: keymaster
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Send Keymaster Request
        run: |
          ARG='{"workflowId":"'$GITHUB_RUN_ID'","secret":"'$MY_SECRET'"}'
          echo $ARG
          curl \
          --fail-with-body \
          -X POST \
          https://keymaster-qa.dev.commandcentral.com/api/v1/token \
          -H "Content-Type: application/json" \
          -d "$ARG" > response.txt || exit 1
          cat response.txt
      - name: Reconfigure GitHub authentication
        run: |
          IAT=$(cat response.txt | jq .data.token)
          echo IAT=${IAT}
          BASIC_AUTH=$(echo -n :${IAT} | base64)
          git config --replace-all http.$(git config --get remote.origin.url).extraheader "AUTHORIZATION: basic ${BASIC_AUTH}"
          git config --unset http.https://github.com/.extraheader
          git config --list
          git remote show origin
          git fetch
    env:
      MY_SECRET: ${{ secrets.DEFAULT }}
