on:
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    environment: keymaster
    steps:
      - name: Send Keymaster Request
        run: |
          ARG='{"workflowId":"'$GITHUB_RUN_ID'","secret":"'$MY_SECRET'"}'
          echo $ARG
          curl \
          -X POST \
          http://malkinhome.duckdns.org:3000/api/token \
          -H "Content-Type: application/json" \
          -d "$ARG" > response.txt
          cat response.txt
      - name: Reconfigure GitHub authentication
        run: |
          IAT=$(cat response.txt | jq .data.token)
          echo IAT=${IAT}
          git config --replace-all http.$(git config --get remote.origin.url).extraheader "AUTHORIZATION: basic ${IAT}"
          git config --unset http.https://github.com/.extraheader
          git pull
    env:
      MY_SECRET: ${{ secrets.DEFAULT }}
